// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: events_statistics.proto

package events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	IsDeleted     bool                   `protobuf:"varint,7,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_events_statistics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_events_statistics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_events_statistics_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *User) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

type UserCreated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCreated) Reset() {
	*x = UserCreated{}
	mi := &file_events_statistics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCreated) ProtoMessage() {}

func (x *UserCreated) ProtoReflect() protoreflect.Message {
	mi := &file_events_statistics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCreated.ProtoReflect.Descriptor instead.
func (*UserCreated) Descriptor() ([]byte, []int) {
	return file_events_statistics_proto_rawDescGZIP(), []int{1}
}

func (x *UserCreated) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type UserUpdated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserUpdated) Reset() {
	*x = UserUpdated{}
	mi := &file_events_statistics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUpdated) ProtoMessage() {}

func (x *UserUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_events_statistics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUpdated.ProtoReflect.Descriptor instead.
func (*UserUpdated) Descriptor() ([]byte, []int) {
	return file_events_statistics_proto_rawDescGZIP(), []int{2}
}

func (x *UserUpdated) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type UserDeleted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDeleted) Reset() {
	*x = UserDeleted{}
	mi := &file_events_statistics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDeleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDeleted) ProtoMessage() {}

func (x *UserDeleted) ProtoReflect() protoreflect.Message {
	mi := &file_events_statistics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDeleted.ProtoReflect.Descriptor instead.
func (*UserDeleted) Descriptor() ([]byte, []int) {
	return file_events_statistics_proto_rawDescGZIP(), []int{3}
}

func (x *UserDeleted) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GameResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	WinnerId      int64                  `protobuf:"varint,2,opt,name=winner_id,json=winnerId,proto3" json:"winner_id,omitempty"`
	LoserId       int64                  `protobuf:"varint,3,opt,name=loser_id,json=loserId,proto3" json:"loser_id,omitempty"`
	Bet           int64                  `protobuf:"varint,4,opt,name=bet,proto3" json:"bet,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Player1       *PlayerGameResult      `protobuf:"bytes,6,opt,name=player1,proto3" json:"player1,omitempty"`
	Player2       *PlayerGameResult      `protobuf:"bytes,7,opt,name=player2,proto3" json:"player2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameResult) Reset() {
	*x = GameResult{}
	mi := &file_events_statistics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameResult) ProtoMessage() {}

func (x *GameResult) ProtoReflect() protoreflect.Message {
	mi := &file_events_statistics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameResult.ProtoReflect.Descriptor instead.
func (*GameResult) Descriptor() ([]byte, []int) {
	return file_events_statistics_proto_rawDescGZIP(), []int{4}
}

func (x *GameResult) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *GameResult) GetWinnerId() int64 {
	if x != nil {
		return x.WinnerId
	}
	return 0
}

func (x *GameResult) GetLoserId() int64 {
	if x != nil {
		return x.LoserId
	}
	return 0
}

func (x *GameResult) GetBet() int64 {
	if x != nil {
		return x.Bet
	}
	return 0
}

func (x *GameResult) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GameResult) GetPlayer1() *PlayerGameResult {
	if x != nil {
		return x.Player1
	}
	return nil
}

func (x *GameResult) GetPlayer2() *PlayerGameResult {
	if x != nil {
		return x.Player2
	}
	return nil
}

type PlayerGameResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	FinalScore    int32                  `protobuf:"varint,2,opt,name=final_score,json=finalScore,proto3" json:"final_score,omitempty"`
	FinalHand     []string               `protobuf:"bytes,3,rep,name=final_hand,json=finalHand,proto3" json:"final_hand,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerGameResult) Reset() {
	*x = PlayerGameResult{}
	mi := &file_events_statistics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerGameResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerGameResult) ProtoMessage() {}

func (x *PlayerGameResult) ProtoReflect() protoreflect.Message {
	mi := &file_events_statistics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerGameResult.ProtoReflect.Descriptor instead.
func (*PlayerGameResult) Descriptor() ([]byte, []int) {
	return file_events_statistics_proto_rawDescGZIP(), []int{5}
}

func (x *PlayerGameResult) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerGameResult) GetFinalScore() int32 {
	if x != nil {
		return x.FinalScore
	}
	return 0
}

func (x *PlayerGameResult) GetFinalHand() []string {
	if x != nil {
		return x.FinalHand
	}
	return nil
}

var File_events_statistics_proto protoreflect.FileDescriptor

const file_events_statistics_proto_rawDesc = "" +
	"\n" +
	"\x17events_statistics.proto\x12\n" +
	"events_svc\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdd\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\a \x01(\bR\tisDeleted\"3\n" +
	"\vUserCreated\x12$\n" +
	"\x04user\x18\x01 \x01(\v2\x10.events_svc.UserR\x04user\"3\n" +
	"\vUserUpdated\x12$\n" +
	"\x04user\x18\x01 \x01(\v2\x10.events_svc.UserR\x04user\"\x1d\n" +
	"\vUserDeleted\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x9a\x02\n" +
	"\n" +
	"GameResult\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1b\n" +
	"\twinner_id\x18\x02 \x01(\x03R\bwinnerId\x12\x19\n" +
	"\bloser_id\x18\x03 \x01(\x03R\aloserId\x12\x10\n" +
	"\x03bet\x18\x04 \x01(\x03R\x03bet\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x126\n" +
	"\aplayer1\x18\x06 \x01(\v2\x1c.events_svc.PlayerGameResultR\aplayer1\x126\n" +
	"\aplayer2\x18\a \x01(\v2\x1c.events_svc.PlayerGameResultR\aplayer2\"o\n" +
	"\x10PlayerGameResult\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\x1f\n" +
	"\vfinal_score\x18\x02 \x01(\x05R\n" +
	"finalScore\x12\x1d\n" +
	"\n" +
	"final_hand\x18\x03 \x03(\tR\tfinalHandBAZ?auth-service/internal/adapter/grpc/server/frontend/proto/eventsb\x06proto3"

var (
	file_events_statistics_proto_rawDescOnce sync.Once
	file_events_statistics_proto_rawDescData []byte
)

func file_events_statistics_proto_rawDescGZIP() []byte {
	file_events_statistics_proto_rawDescOnce.Do(func() {
		file_events_statistics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_events_statistics_proto_rawDesc), len(file_events_statistics_proto_rawDesc)))
	})
	return file_events_statistics_proto_rawDescData
}

var file_events_statistics_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_events_statistics_proto_goTypes = []any{
	(*User)(nil),                  // 0: events_svc.User
	(*UserCreated)(nil),           // 1: events_svc.UserCreated
	(*UserUpdated)(nil),           // 2: events_svc.UserUpdated
	(*UserDeleted)(nil),           // 3: events_svc.UserDeleted
	(*GameResult)(nil),            // 4: events_svc.GameResult
	(*PlayerGameResult)(nil),      // 5: events_svc.PlayerGameResult
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_events_statistics_proto_depIdxs = []int32{
	6, // 0: events_svc.User.created_at:type_name -> google.protobuf.Timestamp
	6, // 1: events_svc.User.updated_at:type_name -> google.protobuf.Timestamp
	0, // 2: events_svc.UserCreated.user:type_name -> events_svc.User
	0, // 3: events_svc.UserUpdated.user:type_name -> events_svc.User
	6, // 4: events_svc.GameResult.created_at:type_name -> google.protobuf.Timestamp
	5, // 5: events_svc.GameResult.player1:type_name -> events_svc.PlayerGameResult
	5, // 6: events_svc.GameResult.player2:type_name -> events_svc.PlayerGameResult
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_events_statistics_proto_init() }
func file_events_statistics_proto_init() {
	if File_events_statistics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_statistics_proto_rawDesc), len(file_events_statistics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_statistics_proto_goTypes,
		DependencyIndexes: file_events_statistics_proto_depIdxs,
		MessageInfos:      file_events_statistics_proto_msgTypes,
	}.Build()
	File_events_statistics_proto = out.File
	file_events_statistics_proto_goTypes = nil
	file_events_statistics_proto_depIdxs = nil
}
