// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: events_email.proto

package events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmailSendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	To            string                 `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailSendRequest) Reset() {
	*x = EmailSendRequest{}
	mi := &file_events_email_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailSendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailSendRequest) ProtoMessage() {}

func (x *EmailSendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_events_email_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailSendRequest.ProtoReflect.Descriptor instead.
func (*EmailSendRequest) Descriptor() ([]byte, []int) {
	return file_events_email_proto_rawDescGZIP(), []int{0}
}

func (x *EmailSendRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *EmailSendRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *EmailSendRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

var File_events_email_proto protoreflect.FileDescriptor

const file_events_email_proto_rawDesc = "" +
	"\n" +
	"\x12events_email.proto\x12\n" +
	"events_svc\x1a\x1fgoogle/protobuf/timestamp.proto\"P\n" +
	"\x10EmailSendRequest\x12\x0e\n" +
	"\x02to\x18\x01 \x01(\tR\x02to\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04bodyB)Z'email_svc/internal/adapter/proto/eventsb\x06proto3"

var (
	file_events_email_proto_rawDescOnce sync.Once
	file_events_email_proto_rawDescData []byte
)

func file_events_email_proto_rawDescGZIP() []byte {
	file_events_email_proto_rawDescOnce.Do(func() {
		file_events_email_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_events_email_proto_rawDesc), len(file_events_email_proto_rawDesc)))
	})
	return file_events_email_proto_rawDescData
}

var file_events_email_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_events_email_proto_goTypes = []any{
	(*EmailSendRequest)(nil), // 0: events_svc.EmailSendRequest
}
var file_events_email_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_events_email_proto_init() }
func file_events_email_proto_init() {
	if File_events_email_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_email_proto_rawDesc), len(file_events_email_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_email_proto_goTypes,
		DependencyIndexes: file_events_email_proto_depIdxs,
		MessageInfos:      file_events_email_proto_msgTypes,
	}.Build()
	File_events_email_proto = out.File
	file_events_email_proto_goTypes = nil
	file_events_email_proto_depIdxs = nil
}
