// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --- General Game Stats ---
type GetGeneralGameStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGeneralGameStatsRequest) Reset() {
	*x = GetGeneralGameStatsRequest{}
	mi := &file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGeneralGameStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGeneralGameStatsRequest) ProtoMessage() {}

func (x *GetGeneralGameStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGeneralGameStatsRequest.ProtoReflect.Descriptor instead.
func (*GetGeneralGameStatsRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

type GeneralGameStats struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TotalUsers       int64                  `protobuf:"varint,1,opt,name=total_users,json=totalUsers,proto3" json:"total_users,omitempty"`
	TotalGamesPlayed int64                  `protobuf:"varint,2,opt,name=total_games_played,json=totalGamesPlayed,proto3" json:"total_games_played,omitempty"`
	TotalBetAmount   int64                  `protobuf:"varint,3,opt,name=total_bet_amount,json=totalBetAmount,proto3" json:"total_bet_amount,omitempty"`
	LastUpdatedAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_updated_at,json=lastUpdatedAt,proto3" json:"last_updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GeneralGameStats) Reset() {
	*x = GeneralGameStats{}
	mi := &file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneralGameStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneralGameStats) ProtoMessage() {}

func (x *GeneralGameStats) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneralGameStats.ProtoReflect.Descriptor instead.
func (*GeneralGameStats) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *GeneralGameStats) GetTotalUsers() int64 {
	if x != nil {
		return x.TotalUsers
	}
	return 0
}

func (x *GeneralGameStats) GetTotalGamesPlayed() int64 {
	if x != nil {
		return x.TotalGamesPlayed
	}
	return 0
}

func (x *GeneralGameStats) GetTotalBetAmount() int64 {
	if x != nil {
		return x.TotalBetAmount
	}
	return 0
}

func (x *GeneralGameStats) GetLastUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdatedAt
	}
	return nil
}

type GetGeneralGameStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *GeneralGameStats      `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGeneralGameStatsResponse) Reset() {
	*x = GetGeneralGameStatsResponse{}
	mi := &file_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGeneralGameStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGeneralGameStatsResponse) ProtoMessage() {}

func (x *GetGeneralGameStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGeneralGameStatsResponse.ProtoReflect.Descriptor instead.
func (*GetGeneralGameStatsResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetGeneralGameStatsResponse) GetStats() *GeneralGameStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

// --- User Game Stats ---
type GetUserGameStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserGameStatsRequest) Reset() {
	*x = GetUserGameStatsRequest{}
	mi := &file_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserGameStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserGameStatsRequest) ProtoMessage() {}

func (x *GetUserGameStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserGameStatsRequest.ProtoReflect.Descriptor instead.
func (*GetUserGameStatsRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserGameStatsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UserGameStats struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GamesPlayed      int64                  `protobuf:"varint,2,opt,name=games_played,json=gamesPlayed,proto3" json:"games_played,omitempty"`
	GamesWon         int64                  `protobuf:"varint,3,opt,name=games_won,json=gamesWon,proto3" json:"games_won,omitempty"`
	GamesLost        int64                  `protobuf:"varint,4,opt,name=games_lost,json=gamesLost,proto3" json:"games_lost,omitempty"`
	GamesDrawn       int64                  `protobuf:"varint,5,opt,name=games_drawn,json=gamesDrawn,proto3" json:"games_drawn,omitempty"`
	TotalBet         int64                  `protobuf:"varint,6,opt,name=total_bet,json=totalBet,proto3" json:"total_bet,omitempty"`
	TotalWinnings    int64                  `protobuf:"varint,7,opt,name=total_winnings,json=totalWinnings,proto3" json:"total_winnings,omitempty"`
	TotalLosses      int64                  `protobuf:"varint,8,opt,name=total_losses,json=totalLosses,proto3" json:"total_losses,omitempty"`
	WinRate          float64                `protobuf:"fixed64,9,opt,name=win_rate,json=winRate,proto3" json:"win_rate,omitempty"`     // float64 maps to double
	LossRate         float64                `protobuf:"fixed64,10,opt,name=loss_rate,json=lossRate,proto3" json:"loss_rate,omitempty"` // float64 maps to double
	WinStreak        int64                  `protobuf:"varint,11,opt,name=win_streak,json=winStreak,proto3" json:"win_streak,omitempty"`
	LossStreak       int64                  `protobuf:"varint,12,opt,name=loss_streak,json=lossStreak,proto3" json:"loss_streak,omitempty"`
	LastGamePlayedAt *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=last_game_played_at,json=lastGamePlayedAt,proto3" json:"last_game_played_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UserGameStats) Reset() {
	*x = UserGameStats{}
	mi := &file_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserGameStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGameStats) ProtoMessage() {}

func (x *UserGameStats) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGameStats.ProtoReflect.Descriptor instead.
func (*UserGameStats) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{4}
}

func (x *UserGameStats) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserGameStats) GetGamesPlayed() int64 {
	if x != nil {
		return x.GamesPlayed
	}
	return 0
}

func (x *UserGameStats) GetGamesWon() int64 {
	if x != nil {
		return x.GamesWon
	}
	return 0
}

func (x *UserGameStats) GetGamesLost() int64 {
	if x != nil {
		return x.GamesLost
	}
	return 0
}

func (x *UserGameStats) GetGamesDrawn() int64 {
	if x != nil {
		return x.GamesDrawn
	}
	return 0
}

func (x *UserGameStats) GetTotalBet() int64 {
	if x != nil {
		return x.TotalBet
	}
	return 0
}

func (x *UserGameStats) GetTotalWinnings() int64 {
	if x != nil {
		return x.TotalWinnings
	}
	return 0
}

func (x *UserGameStats) GetTotalLosses() int64 {
	if x != nil {
		return x.TotalLosses
	}
	return 0
}

func (x *UserGameStats) GetWinRate() float64 {
	if x != nil {
		return x.WinRate
	}
	return 0
}

func (x *UserGameStats) GetLossRate() float64 {
	if x != nil {
		return x.LossRate
	}
	return 0
}

func (x *UserGameStats) GetWinStreak() int64 {
	if x != nil {
		return x.WinStreak
	}
	return 0
}

func (x *UserGameStats) GetLossStreak() int64 {
	if x != nil {
		return x.LossStreak
	}
	return 0
}

func (x *UserGameStats) GetLastGamePlayedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastGamePlayedAt
	}
	return nil
}

type GetUserGameStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *UserGameStats         `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserGameStatsResponse) Reset() {
	*x = GetUserGameStatsResponse{}
	mi := &file_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserGameStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserGameStatsResponse) ProtoMessage() {}

func (x *GetUserGameStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserGameStatsResponse.ProtoReflect.Descriptor instead.
func (*GetUserGameStatsResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserGameStatsResponse) GetStats() *UserGameStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

// --- Leaderboard ---
type GetLeaderboardRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	LeaderboardType string                 `protobuf:"bytes,1,opt,name=leaderboard_type,json=leaderboardType,proto3" json:"leaderboard_type,omitempty"`
	Limit           int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetLeaderboardRequest) Reset() {
	*x = GetLeaderboardRequest{}
	mi := &file_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeaderboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaderboardRequest) ProtoMessage() {}

func (x *GetLeaderboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaderboardRequest.ProtoReflect.Descriptor instead.
func (*GetLeaderboardRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetLeaderboardRequest) GetLeaderboardType() string {
	if x != nil {
		return x.LeaderboardType
	}
	return ""
}

func (x *GetLeaderboardRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type LeaderboardEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"` // Optional
	Score         int64                  `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	Rank          int32                  `protobuf:"varint,4,opt,name=rank,proto3" json:"rank,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderboardEntry) Reset() {
	*x = LeaderboardEntry{}
	mi := &file_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderboardEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderboardEntry) ProtoMessage() {}

func (x *LeaderboardEntry) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderboardEntry.ProtoReflect.Descriptor instead.
func (*LeaderboardEntry) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{7}
}

func (x *LeaderboardEntry) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LeaderboardEntry) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LeaderboardEntry) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *LeaderboardEntry) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

type Leaderboard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Entries       []*LeaderboardEntry    `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Leaderboard) Reset() {
	*x = Leaderboard{}
	mi := &file_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Leaderboard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Leaderboard) ProtoMessage() {}

func (x *Leaderboard) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Leaderboard.ProtoReflect.Descriptor instead.
func (*Leaderboard) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{8}
}

func (x *Leaderboard) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Leaderboard) GetEntries() []*LeaderboardEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type GetLeaderboardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Leaderboard   *Leaderboard           `protobuf:"bytes,1,opt,name=leaderboard,proto3" json:"leaderboard,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeaderboardResponse) Reset() {
	*x = GetLeaderboardResponse{}
	mi := &file_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeaderboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaderboardResponse) ProtoMessage() {}

func (x *GetLeaderboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaderboardResponse.ProtoReflect.Descriptor instead.
func (*GetLeaderboardResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetLeaderboardResponse) GetLeaderboard() *Leaderboard {
	if x != nil {
		return x.Leaderboard
	}
	return nil
}

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\n" +
	"statistics\x1a\x1fgoogle/protobuf/timestamp.proto\"\x1c\n" +
	"\x1aGetGeneralGameStatsRequest\"\xcf\x01\n" +
	"\x10GeneralGameStats\x12\x1f\n" +
	"\vtotal_users\x18\x01 \x01(\x03R\n" +
	"totalUsers\x12,\n" +
	"\x12total_games_played\x18\x02 \x01(\x03R\x10totalGamesPlayed\x12(\n" +
	"\x10total_bet_amount\x18\x03 \x01(\x03R\x0etotalBetAmount\x12B\n" +
	"\x0flast_updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\rlastUpdatedAt\"Q\n" +
	"\x1bGetGeneralGameStatsResponse\x122\n" +
	"\x05stats\x18\x01 \x01(\v2\x1c.statistics.GeneralGameStatsR\x05stats\"2\n" +
	"\x17GetUserGameStatsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\xd2\x03\n" +
	"\rUserGameStats\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12!\n" +
	"\fgames_played\x18\x02 \x01(\x03R\vgamesPlayed\x12\x1b\n" +
	"\tgames_won\x18\x03 \x01(\x03R\bgamesWon\x12\x1d\n" +
	"\n" +
	"games_lost\x18\x04 \x01(\x03R\tgamesLost\x12\x1f\n" +
	"\vgames_drawn\x18\x05 \x01(\x03R\n" +
	"gamesDrawn\x12\x1b\n" +
	"\ttotal_bet\x18\x06 \x01(\x03R\btotalBet\x12%\n" +
	"\x0etotal_winnings\x18\a \x01(\x03R\rtotalWinnings\x12!\n" +
	"\ftotal_losses\x18\b \x01(\x03R\vtotalLosses\x12\x19\n" +
	"\bwin_rate\x18\t \x01(\x01R\awinRate\x12\x1b\n" +
	"\tloss_rate\x18\n" +
	" \x01(\x01R\blossRate\x12\x1d\n" +
	"\n" +
	"win_streak\x18\v \x01(\x03R\twinStreak\x12\x1f\n" +
	"\vloss_streak\x18\f \x01(\x03R\n" +
	"lossStreak\x12I\n" +
	"\x13last_game_played_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\x10lastGamePlayedAt\"K\n" +
	"\x18GetUserGameStatsResponse\x12/\n" +
	"\x05stats\x18\x01 \x01(\v2\x19.statistics.UserGameStatsR\x05stats\"X\n" +
	"\x15GetLeaderboardRequest\x12)\n" +
	"\x10leaderboard_type\x18\x01 \x01(\tR\x0fleaderboardType\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"q\n" +
	"\x10LeaderboardEntry\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x03R\x05score\x12\x12\n" +
	"\x04rank\x18\x04 \x01(\x05R\x04rank\"Y\n" +
	"\vLeaderboard\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x126\n" +
	"\aentries\x18\x02 \x03(\v2\x1c.statistics.LeaderboardEntryR\aentries\"S\n" +
	"\x16GetLeaderboardResponse\x129\n" +
	"\vleaderboard\x18\x01 \x01(\v2\x17.statistics.LeaderboardR\vleaderboard2\xb3\x02\n" +
	"\x11StatisticsService\x12f\n" +
	"\x13GetGeneralGameStats\x12&.statistics.GetGeneralGameStatsRequest\x1a'.statistics.GetGeneralGameStatsResponse\x12]\n" +
	"\x10GetUserGameStats\x12#.statistics.GetUserGameStatsRequest\x1a$.statistics.GetUserGameStatsResponse\x12W\n" +
	"\x0eGetLeaderboard\x12!.statistics.GetLeaderboardRequest\x1a\".statistics.GetLeaderboardResponseB8Z6statistics/internal/adapter/grpc/server/frontend/protob\x06proto3"

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData []byte
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)))
	})
	return file_service_proto_rawDescData
}

var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_service_proto_goTypes = []any{
	(*GetGeneralGameStatsRequest)(nil),  // 0: statistics.GetGeneralGameStatsRequest
	(*GeneralGameStats)(nil),            // 1: statistics.GeneralGameStats
	(*GetGeneralGameStatsResponse)(nil), // 2: statistics.GetGeneralGameStatsResponse
	(*GetUserGameStatsRequest)(nil),     // 3: statistics.GetUserGameStatsRequest
	(*UserGameStats)(nil),               // 4: statistics.UserGameStats
	(*GetUserGameStatsResponse)(nil),    // 5: statistics.GetUserGameStatsResponse
	(*GetLeaderboardRequest)(nil),       // 6: statistics.GetLeaderboardRequest
	(*LeaderboardEntry)(nil),            // 7: statistics.LeaderboardEntry
	(*Leaderboard)(nil),                 // 8: statistics.Leaderboard
	(*GetLeaderboardResponse)(nil),      // 9: statistics.GetLeaderboardResponse
	(*timestamppb.Timestamp)(nil),       // 10: google.protobuf.Timestamp
}
var file_service_proto_depIdxs = []int32{
	10, // 0: statistics.GeneralGameStats.last_updated_at:type_name -> google.protobuf.Timestamp
	1,  // 1: statistics.GetGeneralGameStatsResponse.stats:type_name -> statistics.GeneralGameStats
	10, // 2: statistics.UserGameStats.last_game_played_at:type_name -> google.protobuf.Timestamp
	4,  // 3: statistics.GetUserGameStatsResponse.stats:type_name -> statistics.UserGameStats
	7,  // 4: statistics.Leaderboard.entries:type_name -> statistics.LeaderboardEntry
	8,  // 5: statistics.GetLeaderboardResponse.leaderboard:type_name -> statistics.Leaderboard
	0,  // 6: statistics.StatisticsService.GetGeneralGameStats:input_type -> statistics.GetGeneralGameStatsRequest
	3,  // 7: statistics.StatisticsService.GetUserGameStats:input_type -> statistics.GetUserGameStatsRequest
	6,  // 8: statistics.StatisticsService.GetLeaderboard:input_type -> statistics.GetLeaderboardRequest
	2,  // 9: statistics.StatisticsService.GetGeneralGameStats:output_type -> statistics.GetGeneralGameStatsResponse
	5,  // 10: statistics.StatisticsService.GetUserGameStats:output_type -> statistics.GetUserGameStatsResponse
	9,  // 11: statistics.StatisticsService.GetLeaderboard:output_type -> statistics.GetLeaderboardResponse
	9,  // [9:12] is the sub-list for method output_type
	6,  // [6:9] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
