// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: events_game.proto

package events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GameResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	WinnerId      int64                  `protobuf:"varint,2,opt,name=winner_id,json=winnerId,proto3" json:"winner_id,omitempty"`
	LoserId       int64                  `protobuf:"varint,3,opt,name=loser_id,json=loserId,proto3" json:"loser_id,omitempty"`
	Bet           int64                  `protobuf:"varint,4,opt,name=bet,proto3" json:"bet,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Player1       *PlayerGameResult      `protobuf:"bytes,6,opt,name=player1,proto3" json:"player1,omitempty"`
	Player2       *PlayerGameResult      `protobuf:"bytes,7,opt,name=player2,proto3" json:"player2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameResult) Reset() {
	*x = GameResult{}
	mi := &file_events_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameResult) ProtoMessage() {}

func (x *GameResult) ProtoReflect() protoreflect.Message {
	mi := &file_events_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameResult.ProtoReflect.Descriptor instead.
func (*GameResult) Descriptor() ([]byte, []int) {
	return file_events_game_proto_rawDescGZIP(), []int{0}
}

func (x *GameResult) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *GameResult) GetWinnerId() int64 {
	if x != nil {
		return x.WinnerId
	}
	return 0
}

func (x *GameResult) GetLoserId() int64 {
	if x != nil {
		return x.LoserId
	}
	return 0
}

func (x *GameResult) GetBet() int64 {
	if x != nil {
		return x.Bet
	}
	return 0
}

func (x *GameResult) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GameResult) GetPlayer1() *PlayerGameResult {
	if x != nil {
		return x.Player1
	}
	return nil
}

func (x *GameResult) GetPlayer2() *PlayerGameResult {
	if x != nil {
		return x.Player2
	}
	return nil
}

type PlayerGameResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	FinalScore    int32                  `protobuf:"varint,2,opt,name=final_score,json=finalScore,proto3" json:"final_score,omitempty"`
	FinalHand     []string               `protobuf:"bytes,3,rep,name=final_hand,json=finalHand,proto3" json:"final_hand,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerGameResult) Reset() {
	*x = PlayerGameResult{}
	mi := &file_events_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerGameResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerGameResult) ProtoMessage() {}

func (x *PlayerGameResult) ProtoReflect() protoreflect.Message {
	mi := &file_events_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerGameResult.ProtoReflect.Descriptor instead.
func (*PlayerGameResult) Descriptor() ([]byte, []int) {
	return file_events_game_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerGameResult) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerGameResult) GetFinalScore() int32 {
	if x != nil {
		return x.FinalScore
	}
	return 0
}

func (x *PlayerGameResult) GetFinalHand() []string {
	if x != nil {
		return x.FinalHand
	}
	return nil
}

var File_events_game_proto protoreflect.FileDescriptor

const file_events_game_proto_rawDesc = "" +
	"\n" +
	"\x11events_game.proto\x12\n" +
	"events_svc\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9a\x02\n" +
	"\n" +
	"GameResult\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1b\n" +
	"\twinner_id\x18\x02 \x01(\x03R\bwinnerId\x12\x19\n" +
	"\bloser_id\x18\x03 \x01(\x03R\aloserId\x12\x10\n" +
	"\x03bet\x18\x04 \x01(\x03R\x03bet\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x126\n" +
	"\aplayer1\x18\x06 \x01(\v2\x1c.events_svc.PlayerGameResultR\aplayer1\x126\n" +
	"\aplayer2\x18\a \x01(\v2\x1c.events_svc.PlayerGameResultR\aplayer2\"o\n" +
	"\x10PlayerGameResult\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\x1f\n" +
	"\vfinal_score\x18\x02 \x01(\x05R\n" +
	"finalScore\x12\x1d\n" +
	"\n" +
	"final_hand\x18\x03 \x03(\tR\tfinalHandB=Z;game_svc/internal/adapter/grpc/server/frontend/proto/eventsb\x06proto3"

var (
	file_events_game_proto_rawDescOnce sync.Once
	file_events_game_proto_rawDescData []byte
)

func file_events_game_proto_rawDescGZIP() []byte {
	file_events_game_proto_rawDescOnce.Do(func() {
		file_events_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_events_game_proto_rawDesc), len(file_events_game_proto_rawDesc)))
	})
	return file_events_game_proto_rawDescData
}

var file_events_game_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_events_game_proto_goTypes = []any{
	(*GameResult)(nil),            // 0: events_svc.GameResult
	(*PlayerGameResult)(nil),      // 1: events_svc.PlayerGameResult
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_events_game_proto_depIdxs = []int32{
	2, // 0: events_svc.GameResult.created_at:type_name -> google.protobuf.Timestamp
	1, // 1: events_svc.GameResult.player1:type_name -> events_svc.PlayerGameResult
	1, // 2: events_svc.GameResult.player2:type_name -> events_svc.PlayerGameResult
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_events_game_proto_init() }
func file_events_game_proto_init() {
	if File_events_game_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_game_proto_rawDesc), len(file_events_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_game_proto_goTypes,
		DependencyIndexes: file_events_game_proto_depIdxs,
		MessageInfos:      file_events_game_proto_msgTypes,
	}.Build()
	File_events_game_proto = out.File
	file_events_game_proto_goTypes = nil
	file_events_game_proto_depIdxs = nil
}
